version: '3.4'

services:
  server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Asia/Krasnoyarsk
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  
  client:
    ports:
      - "5001:3000"

  proxy:
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"

  postgres_db:
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      -  "5433:5433"
    command: -p 5433
volumes:
  postgres-data:

